#!/bin/bash

# stunnel configuration script
# This script dynamically generates a stunnel configuration file based on environment variables
# and starts the stunnel service

set -euo pipefail

# Check if required environment variables are set
if [ -z "${STUNNEL_SERVICE:-}" ]; then
    echo "ERROR: STUNNEL_SERVICE variable not defined" >&2
    echo "Usage: Set STUNNEL_SERVICE to the name of your stunnel service" >&2
    exit 1
fi

if [ -z "${STUNNEL_ACCEPT:-}" ]; then
    echo "ERROR: STUNNEL_ACCEPT variable not defined" >&2
    echo "Usage: Set STUNNEL_ACCEPT to the port to accept connections on (e.g., 8443)" >&2
    exit 1
fi

if [ -z "${STUNNEL_CONNECT:-}" ]; then
    echo "ERROR: STUNNEL_CONNECT variable not defined" >&2
    echo "Usage: Set STUNNEL_CONNECT to the target host:port (e.g., 127.0.0.1:8080)" >&2
    exit 1
fi

if [ -z "${STUNNEL_PROTO:-}" ]; then
    echo "ERROR: STUNNEL_PROTO variable not defined" >&2
    echo "Usage: Set STUNNEL_PROTO to the protocol (e.g., https)" >&2
    exit 1
fi

echo "INFO: Generating stunnel configuration for service: ${STUNNEL_SERVICE}"

# Generate stunnel configuration file
cat <<EOF > /etc/stunnel/stunnel.conf
# stunnel configuration generated by run_stunnel.sh
foreground = yes

[${STUNNEL_SERVICE}]
protocol = ${STUNNEL_PROTO}
accept = 0.0.0.0:${STUNNEL_ACCEPT}
connect = ${STUNNEL_CONNECT}
cert = /etc/stunnel/stunnel.pem
key = /etc/stunnel/stunnel.pem
EOF

echo "INFO: Starting stunnel with configuration:"
echo "  Service: ${STUNNEL_SERVICE}"
echo "  Protocol: ${STUNNEL_PROTO}"
echo "  Accept: 0.0.0.0:${STUNNEL_ACCEPT}"
echo "  Connect: ${STUNNEL_CONNECT}"

# Start stunnel with the generated configuration
exec stunnel /etc/stunnel/stunnel.conf
