#!/bin/bash

# stunnel configuration script
# This script dynamically generates a stunnel configuration file based on environment variables
# and starts the stunnel service

set -euo pipefail

# Check if required environment variables are set
if [ -z "${STUNNEL_SERVICE:-}" ]; then
    echo "ERROR: STUNNEL_SERVICE variable not defined" >&2
    echo "Usage: Set STUNNEL_SERVICE to the name of your stunnel service" >&2
    exit 1
fi

if [ -z "${STUNNEL_ACCEPT:-}" ]; then
    echo "ERROR: STUNNEL_ACCEPT variable not defined" >&2
    echo "Usage: Set STUNNEL_ACCEPT to the port to accept connections on (e.g., 8443)" >&2
    exit 1
fi

echo "INFO: Generating stunnel configuration for service: ${STUNNEL_SERVICE}"

# Generate stunnel configuration file
cat <<EOF > /etc/stunnel/stunnel.conf
# stunnel configuration generated by run_stunnel.sh
foreground = yes

[${STUNNEL_SERVICE}]
protocol = smtp
accept = 0.0.0.0:${STUNNEL_ACCEPT}
connect = 127.0.1:1025
cert = /etc/stunnel/stunnel.pem
key = /etc/stunnel/stunnel.pem
EOF

echo "INFO: Starting stunnel with configuration:"
echo "  Service: ${STUNNEL_SERVICE}"
echo "  Accept: 0.0.0.0:${STUNNEL_ACCEPT}"

# Run mailhog in the background
/root/go/bin/MailHog &

# Start stunnel with the generated configuration
exec stunnel /etc/stunnel/stunnel.conf
